### ISSUE TITLE
Validation messages not showing for blocks after block resource was added and deleted later

### ISSUE THREAD

**Issue by Calebbubune** [FLOIP/flow-builder#202]
**What I did**

- Create a flow with multiple languages & multiple modes (e.g. Voice, SMS and USSD)
- Add a Message block to the builder
- Add all content (e.g. Voice, SMS, USSD) resources for the block
- Save the flow
- Move back to one of the resources for the block
- Delete the resource for the block

**Expected:**

- The resource UI should have a validation text for the missing Message block content
- The resource notification banner should display validation messages related to resource validations.

**What happened**
- There was no validation text for the missing Message block content

Observed that 
- The validation messages on the resource notification banner disappear after the title is entered for the block.
- The various content types still showing the validation messages for the block

**Comment by safydy-r** [comment]
Extra context (After the call we had):
- to reproduce it, we filled the block `title`

**Comment by safydy-r** [comment]
@Calebbubune , I made a fix, pls have a look again ;)

**Comment by Calebbubune** [comment]
Issue has been resolved -- thanks
