### ISSUE TITLE
Users cannot delete/clear resources content for Numeric Response & Open Response block after switching Flow Builder mode from Edit to View mode

### ISSUE THREAD

**Issue by Calebbubune** [FLOIP/flow-builder#203]
**What I did**

- Create a flow with multiple languages & multiple modes (e.g. Voice, SMS and USSD)
- Add  "Numeric Response" & Open Response blocks to the builder
- Fill in contents/details for the blocks

- Switch from the Edit mode to the View mode for the Flow Builder
 
- Switch from the View mode to the Edit mode for the Flow Builder

- Edit the resource content(s) of  "Numeric Response" & "Open Response" blocks

**Expectation**
- The user should be able to edit the block(s) resources data after the flow builder mode switch.

**What I did**
- The user could not edit the block(s) resources data after the flow builder mode switch.

**Comment by safydy-r** [comment]
Thnx for this. I fixed it, pls retest !

**Comment by Calebbubune** [comment]
Thanks @safydy-r, the fix worked.
