### ISSUE TITLE
JQuery requirement error

### ISSUE THREAD

**Issue by smn** [FLOIP/flow-builder#22]
Wanted to take this code base for a spin but am running into issues where after a successful build it seems to be missing a dependency on JQuery.

![Screenshot 2020-12-01 at 11 52 26](https://user-images.githubusercontent.com/1065/100731499-c451b980-33cb-11eb-8cbf-f26b7155f965.png)

Getting this in both Firefox and Chrome. Before I lose myself in Webpack and related build tools, is this a known issue?

**Comment by safydy-r** [comment]
Thank you for pointing this. We're working on it. Will keep you informed

**Comment by smn** [comment]
thanks! Appreciate that.
